using Jellyfin.Plugin.AIOStreams.Configuration;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Common.Plugins;
using MediaBrowser.Model.Plugins;
using MediaBrowser.Model.Serialization;

namespace Jellyfin.Plugin.AIOStreams;

/// <summary>
/// AIOStreams plugin: turns a self-hosted AIOStreams instance into a browsable Jellyfin library
/// via generated .strm files.
/// </summary>
public class Plugin : BasePlugin<PluginConfiguration>, IHasWebPages
{
    private readonly Guid _id = new("3a9f7c1e-5b6d-4e8f-9c2a-1d4b5e6f7a8b");

    public Plugin(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer)
        : base(applicationPaths, xmlSerializer)
    {
        Instance = this;
    }

    /// <summary>
    /// Gets the current plugin instance.
    /// </summary>
    public static Plugin? Instance { get; private set; }

    public override Guid Id => _id;

    public override string Name => "Jellyio Streams";

    public override string Description => "Stream Stremio-addon content from your self-hosted AIOStreams instance.";

    /// <summary>
    /// Gets the folder where .strm files are generated by default.
    /// </summary>
    public string DefaultOutputPath => Path.Combine(ApplicationPaths.DataPath, "aiostreams");

    /// <summary>
    /// Gets the resolved output path, honoring a custom override from the configuration.
    /// </summary>
    public string ResolvedOutputPath
    {
        get
        {
            var configured = Configuration.OutputPath?.Trim();
            return string.IsNullOrEmpty(configured)
                ? DefaultOutputPath
                : Path.GetFullPath(configured);
        }
    }

    public IEnumerable<PluginPageInfo> GetPages()
    {
        return new[]
        {
            new PluginPageInfo
            {
                Name = "Jellyio Streams",
                EmbeddedResourcePath = GetType().Namespace + ".Configuration.configPage.html"
            },
            new PluginPageInfo
            {
                Name = "JellyioStreamsSearch",
                DisplayName = "Jellyio Streams",
                EmbeddedResourcePath = GetType().Namespace + ".Web.searchPage.html",
                EnableInMainMenu = true
            }
        };
    }
}
